name: fastbook
channels:
    - fastai
    - pytorch
    - defaults
    - nvidia
    - conda-forge
dependencies:
  - nb_conda_kernels
  - nodejs
  - python>=3.12
  - pytorch=2.6.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.6
  - pip
  - pip:
    - -r requirements.txt