name: fastbook
channels:
    - fastai
    - pytorch
    - defaults
    - nvidia
    - conda-forge
dependencies:
  - jupyterlab
  - nb_conda_kernels
  - nodejs
  - python>=3.12
  - pytorch>=2.5
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip
  - pip:
    - -r requirements.txt